# -*- coding: utf-8 -*-
"""Practice-04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SZrvoDAWvt42gosAJ9BS8OTbNLwT4GNG

> SMIT Task, Project & Assigment's

# Class Eligibility Check (If-Else)

- Is today a class day? (Yes/No)
- Do you have your card? (Yes/No)
- Have you submitted your fees? (Yes/No)
- Is your assignment complete? (Yes/No)

## Result:
- If all conditions are "Yes" → You can attend the class.
- Otherwise → You are not allowed to attend the class.

#Nested if-else
"""

class_day = input("Is today a class day? (Y/N): ")

if class_day == "y":
    card = input("Did you bring your card? (Y/N): ")

    if card == "y":
        fees = input("Have you submitted the fees? (Y/N): ")

        if fees == "y":
            assignment = input("Is the assignment complete? (Y/N): ")

            if assignment == "y":
                print("You can attend the class.")
            else:
                print("Assignment is not complete. You cannot attend the class.")

        else:
            print("Fees are not submitted. You cannot attend the class.")

    else:
        print("You did not bring your card. You cannot attend the class.")

else:
    print("There is no class today (Saturday & Sunday).")

"""# Student Marks Calculator (If-Else)

* Enter your marks for English
* Enter your marks for Math
* Enter your marks for Urdu
* Enter your marks for Science
* Enter your marks for Computer

## Result:

* If all subjects marks are **50 or above** → You are **Pass**
* If any subject marks are **less than 50** → You are **Fail**

## Grade System:

* If percentage is 90 or above → **A+**
* If percentage is 80 or above → **A**
* If percentage is 70 or above → **B**
* If percentage is 60 or above → **C**
* Otherwise → **Failed**

## Output:

* Total marks (out of 500)
* Obtained marks
* Percentage
* Grade
* Final Result (Pass/Fail)

"""

sub1 = int(input("Enter English marks: "))
sub2 = int(input("Enter Math marks: "))
sub3 = int(input("Enter Urdu marks: "))
sub4 = int(input("Enter Science marks: "))
sub5 = int(input("Enter Computer marks: "))

obtain_marks = sub1 + sub2 + sub3 + sub4 + sub5
percentage = (obtain_marks/500) * 100

grade = ""
result = ""

if sub1 >= 50:
    if sub2 >= 50:
        if sub3 >= 50:
            if sub4 >= 50:
                if sub5 >= 50:
                    result = "Pass"
                else:
                    result = "Fail"
            else:
                result = "Fail"
        else:
            result = "Fail"
    else:
        result = "Fail"
else:
    result = "Fail"

if percentage >= 90:
  grade = "A+"
elif percentage>= 80:
  grade = "A"
elif percentage>= 70:
  grade = "B"
elif percentage>= 60:
  grade = "C"
else:
  grade = "Failed"

print(f"""
    total marks : 500
    obtain marks : {obtain_marks}
    percentage : {percentage}
    grade : {grade}
    result : {result}
""")



"""#  Match Making System


## How it Works

* User se basic details li jati hain:

  * My name
  * Girl’s name
  * Age

* Agar age **18 to 25** ke beech ho to further checks hotay hain:

  * Gender check (Female required)
  * Skin colour check (White)
  * Hair colour (Black)
  * Hair length (≤ 5)
  * Height (≤ 5 feet)
  * Weight (≤ 60)
  * Cooking skill (Yes)
  * Language (Urdu / English / Punjabi)
  * Country (Pakistan / India / Germany)

---

## Result

* Agar **saari conditions match ho jayein** →
     `Yes I am Agree`

* Agar koi bhi condition fail ho jaye →
  `Nahi chiya hai !!`


____________________________________


Final Decision:
Yes I am Agree / Nahi chiya hai !!
"""



humra_jawab = ""
my_name = input("My name?? ")
larki_name = input("What is Girl name?? ")
age = int(input("what is Your age "))

if age >= 18 and age <= 25:

        colour = input("What's Colour Enter : White | Brown | Black | Peach ")
        if colour in ["Black", "White", "Peach"]:

            hairs = input("Hair Colour btao? Black | White | Peach | Yellow | Red | Gray : ")
            if hairs in ["Black", "White", "Peach", "Yellow", "Red", "Gray"]:

                hairs_length = int(input("What is the length of your hair?? "))
                if hairs_length <= 5:

                    height = int(input("Enter your Height in Feet?? "))
                    if height <= 6:

                        weight = int(input("Input your Weight?? "))
                        if weight <= 60:

                            cooking = input("Cooking ati ha ya nahi?? Y/N ")
                            if cooking == "y":

                                language = input("What is Your Language?? Urdu | English | Punjabi | Sindhi | Mrthi | Hindi ")
                                if language in ["Urdu", "English", "Punjabi", "Sindhi", "Mrthi", "Hindi"]:

                                    country = input("Enter Your Country?? Pakistan | India | Germany | Bangladesh | Austrilia | America | China")
                                    if country in ["Pakistan", "India", "Germany", "Bangladesh", "Austrilia", "America", "China " ]:
                                        humra_jawab = "Yes I am Agree"

                                    else:
                                        humra_jawab = "Nahi chiya hai !!"

                                else:
                                    humra_jawab = "Nahi chiya hai !!"

                            else:
                                humra_jawab = "Nahi chiya hai !!"

                        else:
                            humra_jawab = "Nahi chiya hai !!"

                    else:
                        humra_jawab = "Nahi chiya hai !!"

                else:
                    humra_jawab = "Nahi chiya hai !!"

            else:
                humra_jawab = "Nahi chiya hai !!"

        else:
            humra_jawab = "Nahi chiya hai !!"

else:
    humra_jawab = "Nahi chiya hai !!"

print(humra_jawab)


print(f"""
================= MATCH RESULT =================

My Name       : {my_name}
Girl Name     : {larki_name}

---------------------------------------------------
 LARKI KE REQUIREMENTS CHECK

Age Requirement : 18 to 25
Your Age        : {age}

Colour          : {colour}
Hair Length     : {hairs_length}
Height          : {height} ft
Weight          : {weight} kg

---------------------------------------------------
FINAL RESULT

{humra_jawab}

---------------------------------------------------
Happy Ending
Best of Luck

===================================================
""")

